import Trecipe from '../../../../shared/models/trecipe';

/**
 * TrecipeListState
 */
export type TrecipeListState = {
    myTrecipes: Array<Trecipe>;
    associatedTrecipes: Array<Trecipe>;
    myAssociatedTrecipes: Array<Trecipe>;
};

export const initialState: TrecipeListState = {
    myTrecipes: [],
    associatedTrecipes: [],
    myAssociatedTrecipes: [],
};

export enum TrecipeListActionCategory {
    CREATE_TRECIPE = '@trecipeList/CREATE_TRECIPE',
    DELETE_TRECIPE = '@trecipeList/DELETE_TRECIPE',
    UPDATE_TRECIPE = '@trecipeList/UPDATE_TRECIPE',
    FETCH_MY_TRECIPES = '@trecipeList/FETCH_MY_TRECIPES',
    FETCH_ASSOCIATED_TRECIPES = '@trecipeList/FETCH_ASSOCIATED_TRECIPES',
    FETCH_MY_ASSOCIATED_TRECIPES = '@trecipeList/FETCH_MY_ASSOCIATED_TRECIPES',
}

export enum TrecipeListActionTypes {
    CREATE_TRECIPE_SUCCESS = '@trecipeList/CREATE_TRECIPE_SUCCESS',
    DELETE_TRECIPE_SUCCESS = '@trecipeList/DELETE_TRECIPE_SUCCESS',
    UPDATE_TRECIPE_SUCCESS = '@trecipeList/UPDATE_TRECIPE_SUCCESS',
    FETCH_MY_TRECIPES_SUCCESS = '@trecipeList/FETCH_MY_TRECIPES_SUCCESS',
    FETCH_ASSOCIATED_TRECIPES_SUCCESS = '@trecipeList/FETCH_ASSOCIATED_TRECIPES_SUCCESS',
    FETCH_MY_ASSOCIATED_TRECIPES_SUCCESS = '@trecipeList/FETCH_MY_ASSOCIATED_TRECIPES_SUCCESS',

    CREATE_TRECIPE_REQUEST = '@trecipeList/CREATE_TRECIPE_REQUEST',
    DELETE_TRECIPE_REQUEST = '@trecipeList/DELETE_TRECIPE_REQUEST',
    UPDATE_TRECIPE_REQUEST = '@trecipeList/UPDATE_TRECIPE_REQUEST',
    FETCH_MY_TRECIPES_REQUEST = '@trecipeList/FETCH_MY_TRECIPES_REQUEST',
    FETCH_ASSOCIATED_TRECIPES_REQUEST = '@trecipeList/FETCH_ASSOCIATED_TRECIPES_REQUEST',
    FETCH_MY_ASSOCIATED_TRECIPES_REQUEST = '@trecipeList/FETCH_MY_ASSOCIATED_TRECIPES_REQUEST',

    CREATE_TRECIPE_FAILURE = '@trecipeList/CREATE_TRECIPE_FAILURE',
    DELETE_TRECIPE_FAILURE = '@trecipeList/DELETE_TRECIPE_FAILURE',
    UPDATE_TRECIPE_FAILURE = '@trecipeList/UPDATE_TRECIPE_FAILURE',
    FETCH_MY_TRECIPES_FAILURE = '@trecipeList/FETCH_MY_TRECIPES_FAILURE',
    FETCH_ASSOCIATED_TRECIPES_FAILURE = '@trecipeList/FETCH_ASSOCIATED_TRECIPES_FAILURE',
    FETCH_MY_ASSOCIATED_TRECIPES_FAILURE = '@trecipeList/FETCH_MY_ASSOCIATED_TRECIPES_FAILURE',
}
