openapi: 3.0.1
info:
  title: server
  description: trecipe backend
  version: 1.0.0
servers:
- url: /api/v1
  description: Dev server
tags:
- name: Trecipes
  description: Trecipe endpoints
paths:
  /trecipes:
    get:
      tags:
      - Trecipes
      summary: Fetch all trecipes
      description: Fetch all trecipes either owned or shared with current user
      responses:
        200:
          description: Returns all trecipes owned or shared with current user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trecipe'
        500:
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
      - Trecipes
      summary: Create a new trecipe
      description: Create a new trecipe with given name, description, and privacy setting
      requestBody:
        description: New Trecipe's name, description, privacy setting
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNewTrecipeDTO'
        required: true
      responses:
        201:
          description: Returns the newly created trecipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trecipe'
        500:
          $ref: '#/components/responses/InternalServerError'

  /trecipes/copy:
    post:
      tags:
        - Trecipes
      summary: Duplicates a trecipe
      description: Duplicates a trecipe with given uuid
      parameters:
        - $ref: '#/components/parameters/queryTrecipeId'
      responses:
        201:
          description: Returns the copy of trecipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trecipe'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'

  /trecipes/{id}:
    get:
      tags:
      - Trecipes
      summary: Gets a trecipe by uuid
      description: Gets a trecipe by uuid
      parameters:
      - $ref: '#/components/parameters/pathId'
      responses:
        200:
          description: Returns the trecipe with the specified uuid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trecipe'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
      - Trecipes
      summary: Updates a trecipe by uuid
      description: Updates a trecipe of given uuid by updated trecipe model
      parameters:
      - $ref: '#/components/parameters/pathId'
      requestBody:
        description: Updated trecipe model
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trecipe'
        required: true
      responses:
        200:
          description: Returns the updated trecipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trecipe'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - Trecipes
      summary: Deletes a trecipe by uuid
      parameters:
        - $ref: '#/components/parameters/pathId'
      responses:
        200:
          $ref: '#/components/responses/Deleted'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
  /destinations:
    post:
      tags:
        - Destinations
      summary: Create new destination
      description: Create a new destination with given placeId
      requestBody:
        description: Destination data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNewDestinationDTO'
      responses:
        201:
          description: Returns the newly created destination
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'
        500:
          $ref: '#/components/responses/InternalServerError'
  /destinations/rate/{id}:
    post:
      tags:
        - Destinations
      summary: Rate a destination
      description: Update the user rating of a destination
      requestBody:
        description: Rating Data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDestinationRatingDTO'
      responses:
        200:
          description: Returns the updated destination
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'
        500:
          $ref: '#/components/responses/InternalServerError'
    get:
      tags:
        - Destinations
      summary: Get destinations by trecipe uuid
      description: Get all destinations in a trecipe with specified uuid
      parameters:
        - $ref: '#/components/parameters/queryTrecipeId'
      responses:
        200:
          description: Returns an array of destinations in trecipe of given uuid
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
  /destinations/{id}:
    get:
      tags:
        - Destinations
      summary: Get destination by uuid
      description: Get destination by uuid
      parameters:
        - $ref: '#/components/parameters/pathId'
      responses:
        200:
          description: Returns the destination given by uuid
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Destination'
        404:
          $ref: '#/components/responses/NotFound'

  /upload:
    post:
      tags:
        - Upload
      summary: Uploads a file to server
      requestBody:
        description: File to upload
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        201:
          description: File upload successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
  /upload/{filename}:
    get:
      tags:
        - Upload
      summary: Gets a file by its filename
      parameters:
        - in: path
          name: filename
          required: true
          schema:
            type: string
          description: The filename to retreive
      responses:
        200:
          description: Retreived file
          content:
            image/*:
              schema:
                type: string
                format: binary

  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}

components:
  parameters:
    pathId:
      name: id
      in: path
      description: uuid
      example: 123e4567-e89b-12d3-a456-426614174000
      required: true
      schema:
        type: string
        format: uuid
    queryTrecipeId:
      name: id
      in: query
      description: Trecipe uuid
      example: 123e4567-e89b-12d3-a456-426614174000
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    Trecipe:
      title: Trecipe
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          example: My Trecipe
        description:
          type: string
          example: Description for my Trecipe
        owner:
          type: string
          example: Team2
        isPrivate:
          type: boolean
          example: true
        collaborators:
            type: array
            items:
              type: string
            example: []
        image:
          type: string
        destinations:
          type: array
          items:
            type: object
            properties:
              destUuid:
                type: string
                example: 234e4567-g72h-2857-a456-426614138477
              completed:
                type: boolean
                example: false
          example: []
    Destination:
      title: Destination
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example: 2h357246-g725-4872-g84m-48692745878567
        name:
          type: string
          example: Sample destination
        category:
          type: array
          items:
            $ref: '#/components/schemas/DestinationCategory'
        geometry:
          $ref: '#/components/schemas/Geometry'
        formattedAddress:
          type: string
          example: 5, 48 Pirrama Rd, Pyrmont NSW 2009, Australia
        formattedPhoneNumber:
          type: string
          example: +61 2 9374 4000
        website:
          type: string
          example: https://www.google.com.au/about/careers/locations/sydney/
        rating:
          $ref: '#/components/schemas/Rating'
        userRatings:
          type: array
          items:
            $ref: '#/components/schemas/UserRating'
        description:
          type: string
          example: Description about this destination
        placeId:
          type: string
          example: ChIJN1t_tDeuEmsRUsoyG83frY4
        photoRefs:
          type: array
          items:
            type: string
          example: [CnRtAAAATLZNl354RwP_9UKbQ_5Psy40texXePv4oAlgP4qNEkdIrkyse7rPXYGd9D_Uj1rVsQdWT4oRz4QrYAJNpFX7rzqqMlZw2h2E2y5IKMUZ7ouD_SlcHxYq1yL4KbKUv3qtWgTK0A6QbGh87GB3sscrHRIQiG2RrmU_jF4tENr9wGS_YxoUSSDrYjWmrNfeEHSGSc3FyhNLlBU]
    DestinationCategory:
      title: DestinationCategory
      type: string
      enum:
        - Food
        - Accommodation
        - Attraction
        - Shopping
        - Others
    Geometry:
      title: Geometry
      type: object
      properties:
        lat:
          type: number
          format: double
          example: 35.929673
        lng:
          type: number
          format: double
          example: -78.948237
      required:
        - lat
        - lng
    Rating:
      title: Rating
      type: number
      format: int64
      minimum: 0
      maximum: 5
      example: 4
    CreateNewTrecipeDTO:
      title: CreateNewTrecipeDTO
      type: object
      properties:
        name:
          type: string
          example: My new Trecipe
        description:
          type: string
          example: Description for my new Trecipe
        isPrivate:
          type: boolean
          example: true
      required:
        - name
        - description
        - isPrivate
    File:
      title: File
      type: object
      properties:
        fieldname:
          type: string
          example: file
        originalname:
          type: string
          example: Screenshot 2020-07-09 01.23.41.png
        encoding:
          type: string
          example: 7bit
        mimetype:
          type: string
          example: image/png
        id:
          type: string
        filename:
          type: string
          example: 238974618927364Screenshot 2020-07-09 01.23.41.png
        bucketName:
          type: string
          example: uploads
        chunkSize:
          type: integer
          example: 261170
        size:
          type: integer
          example: 768613
        md5:
          type: string
          example: c904ef66b72bd29a4e5229724c9fe975
        uploadDate:
          type: string
          example: 2020-07-09T06:50:35.553+00:00
        contentType:
          type: string
          example: image/png
    CreateNewDestinationDTO:
      title: CreateNewDestinationDTO
      type: object
      properties:
        name:
          type: string
          example: Sample destination
        category:
          type: array
          items:
            $ref: '#/components/schemas/DestinationCategory'
        geometry:
          $ref: '#/components/schemas/Geometry'
        formattedAddress:
          type: string
          example: 5, 48 Pirrama Rd, Pyrmont NSW 2009, Australia
        formattedPhoneNumber:
          type: string
          example: +61 2 9374 4000
        website:
          type: string
          example: https://www.google.com.au/about/careers/locations/sydney/
        rating:
          $ref: '#/components/schemas/Rating'
        userRatings:
          type: array
          items:
            $ref: '#/components/schemas/UserRating'
        description:
          type: string
          example: Description about this destination
        placeId:
          type: string
          example: ChIJN1t_tDeuEmsRUsoyG83frY4
        photoRefs:
          type: array
          items:
            type: string
          example: [CnRtAAAATLZNl354RwP_9UKbQ_5Psy40texXePv4oAlgP4qNEkdIrkyse7rPXYGd9D_Uj1rVsQdWT4oRz4QrYAJNpFX7rzqqMlZw2h2E2y5IKMUZ7ouD_SlcHxYq1yL4KbKUv3qtWgTK0A6QbGh87GB3sscrHRIQiG2RrmU_jF4tENr9wGS_YxoUSSDrYjWmrNfeEHSGSc3FyhNLlBU]
      required:
        - placeId
        - name
        - geometry
    UpdateDestinationRatingDTO:
      title: updateDestinationRatingDTO
      type: object
      properties:
        userId:
          type: string
        trecipeId:
          type: string
        rating:
          $ref: '#/components/schemas/Rating'
      required:
        - userId
        - trecipeId
        - rating
    UserRating:
      title: UserRating
      type: object
      properties:
        userId:
          type: string
        rating:
          $ref: '#/components/schemas/Rating'
    Error:
      title: Error
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  responses:
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Deleted:
      description: Operation success
      content:
        application/json:
          schema:
            type: object
            properties:
              deletedCount:
                type: integer
                format: int64