import API, { baseURL } from "../api";
import { AxiosResponse } from 'axios';

interface FileResponse {
    originalName: string;
    filename: string;
    uploadDate: string;
    contentType: string;
}

class UploadService {
    private apiEndpoint = 'upload';

    /**
     * Uploads a file to server as a multi-form data
     * @param file: file to upload
     * @returns filename generated by the server for this file
     */
    public uploadFile(file: File): Promise<string> {
        let data = new FormData();
        data.append('file', file);
        return API.post<{ file: FileResponse }>(`${baseURL}/${this.apiEndpoint}`, data)
            .then((res: AxiosResponse<{ file: FileResponse }>) => {
                return Promise.resolve(res.data.file.filename);
            })
            .catch((err) => {
                return Promise.reject(err);
            });
    }
}

export default new UploadService();
