import { library } from '@fortawesome/fontawesome-svg-core';

import {
    faBorderAll,
    faCheck,
    faChevronDown,
    faChevronUp,
    faLock,
    faMapMarkerAlt,
    faPlusCircle,
    faEdit,
    faCopy,
    faEllipsisH,
    faSearch,
    faLockOpen,
    faCameraRetro,
    faQuestion,
    faStar as fasStar,
    faBars,
    faUtensils,
    faBed,
    faShoppingCart,
    faBinoculars,
    faExternalLinkAlt,
    faMapMarkedAlt,
    faMapMarker,
    faPhone,
} from '@fortawesome/free-solid-svg-icons';
import {
    faQuestionCircle,
    faStar,
    faTrashAlt,
    faWindowMaximize,
} from '@fortawesome/free-regular-svg-icons';
import { faGithub } from '@fortawesome/free-brands-svg-icons';

library.add(
    faPlusCircle,
    faQuestionCircle,
    faCheck,
    faChevronUp,
    faChevronDown,
    faLock,
    faLockOpen,
    faBorderAll,
    faEdit,
    faCopy,
    faTrashAlt,
    faEllipsisH,
    faSearch,
    faMapMarkerAlt,
    faStar,
    faGithub,
    faCameraRetro,
    fasStar,
    faGithub,
    faQuestion,
    faBars,
    faUtensils,
    faBed,
    faShoppingCart,
    faBinoculars,
    faExternalLinkAlt,
    faMapMarkedAlt,
    faMapMarker,
    faPhone,
    faWindowMaximize
);
